### ISSUE TITLE
enable generation of multiple distinctly configured summary plots

### ISSUE THREAD

**Issue by jbloom** [dms-vep/dms-vep-pipeline-3#110]
Write now the pipeline just has an option to create one summary plot.

It might be useful to be able to specify the configuration to create multiple differently named summary plots.

**Comment by Bernadetadad** [comment]
@jbloom this would actually be very useful for H5 data because currently all summary heatmaps get filtered based on 293T entry but that means that 2,6 cell entry heatmap also get's filtered by 293T entry values and so sites enhancing 2,6 entry that are very bad for 293T entry (like Q226L) are all greyed out.
