### ISSUE TITLE
structure annotations on heatmaps

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline-3#119]
@jbloom could structure annotations on heatmaps be added to general dms-vep-pipeline? something like @bblarsen-sci has `here` just using taking annotations from site_numbering_map.csv. Seems like something that could be useful in many instances.

**Comment by jbloom** [comment]
@Bernadetadad, I'm not sure the link you mean to Brendan's Nipah since that is not included, but is it the black overlay bar here [here](https://dms-vep.org/Nipah_Malaysia_RBP_DMS/htmls/E2_entry_heatmap.html)? 

Personally, I think overlays might be better added to static figures manually if that is feasible? Our current interactive plots already allow zooming by region from the zoom bar. For a static plot, I think a visualization like one in [figure 3 here](https://journals.asm.org/doi/full/10.1128/jvi.01329-23) looks better as the domain annotations don't just look like additional heatmap rows. Plus that way you can potentially show overlapping regions, like antigenic regions that are on top of HA head.

Would you be OK just manually adding in that way?

**Comment by Bernadetadad** [comment]
I see, yes I can add it manually.
