### ISSUE TITLE
Fix significant numbers on sliders

### ISSUE THREAD

**Issue by bblarsen-sci** [dms-vep/dms-vep-pipeline-3#136]
This is a super minor issue, but I find the number of significant numbers on the sliders to be overwhelming/distracting, especially in the context of the new pretty landing pages. 

<img width="694" alt="Screenshot 2024-05-14 at 6 35 12 AM" src="https://github.com/dms-vep/dms-vep-pipeline-3/assets/89543163/95b8eee7-6bac-4ef5-83a1-a851d45c86de">

**Comment by jbloom** [comment]
You can manually set a max using `slider_binding_range_kwargs` like this (https://github.com/dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/blob/main/data/antibody_escape_config.yml#L795-L803), but this requires you to choose a max. If you just let `altair` auto select the max from the data it will have many figures.

So this issue is really solved from a pipeline perspective, it is just a matter of going to the specific repo in question and hardcoding in the max value, which should only be done near the end because otherwise you might code a value that doesn't make sense given the data range.
