### ISSUE TITLE
Allowing re-use of barcode run files in barcode_runs.csv

### ISSUE THREAD

**Issue by arjunaditham** [dms-vep/dms-vep-pipeline-3#147]
For my antibody selections, I concatenate my replicates of my 'no antibody' library virus in `barcode_runs.csv` into a single run. On occasion, these 'no antibody' experimental groups also double as functional selections. For analyzing functional selections, I want to keep these replicates separate. For the antibody selections, I would like to concatenate them into a single run for consistency with other prior analyses.

I wanted to ask if there's a way around the rule where `fastq` files cannot be repeated `barcode_runs.csv` file so that I could implement this. Either the rule could be waived, so that I can create an extra row in `barcode_runs.csv` with all of these files to analyze escape data, or maybe `antibody_escape_config.yml` can allow multiple runs to be used for the `no_antibody_sample` group?

**Comment by jbloom** [comment]
@arjunaditham, this should be addressed by #148 which adds an optional `duplicate_fastq_R1` option in `config.yaml`.

Can be set to "error", "warn" or "ignore" to specify what happens if the same FASTQ is used in multiple samples. Defaults to "error" if not specified.

So in your case, you would want to add:
```
duplicate_fastq_R1: ignore
```
or
```
duplicate_fastq_R1: warn
```
depending on whether you want to be warned about the duplicates or not.

Note you have to pull the latest pipeline version first.

I've closed this issue, but please re-open and indicate if you run into any more issues using this.
