### ISSUE TITLE
Align zoom bar to line plot 

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline-3#149]
This is a small aesthetic thing but I've noticed that the zoom bar does not quite align with the correct sites on line plot. E.g. as illustrated below 518 site is in the RBD but it looks like it's in the 'other region'. If possible would be nice if the two would align.
<img width="998" alt="image" src="https://github.com/user-attachments/assets/05c25407-93d8-449b-8008-ba11fb5120cd">

**Comment by jbloom** [comment]
@Bernadetadad, I am pretty sure this issue is already fixed, and you are seeing a problem simply because you are using an outdated version of `dms-vep-pipeline-3`. 

If this is the XBB.1.5 children sera analysis, it looks like you have version 3.6.3 of the pipeline there whereas the latest version is 3.16.0.

I think the issue you are noting was fixed in version 3.11.0, see the [CHANGELOG](https://github.com/dms-vep/dms-vep-pipeline-3/blob/main/CHANGELOG.md). Note also the handful of other backwards-incompatible changes in that version per the CHANGELOG.

I'm closing this issue, re-open if updating the pipeline version doesn't fix things.
