### ISSUE TITLE
Analysis of variant counts notebook no longer showing up in /docs

### ISSUE THREAD

**Issue by bblarsen-sci** [dms-vep/dms-vep-pipeline-3#164]
I noticed that the notebook [Analysis of variant counts](https://github.com/dms-vep/dms-vep-pipeline-3/blob/main/notebooks/analyze_variant_counts.ipynb) is no longer showing up in in the`/docs` for recent versions of `dms-vep-pipeline-3`. 

It used to show up under 'Analysis notebooks'
![Screenshot 2024-12-06 at 10 28 50 AM](https://github.com/user-attachments/assets/d4b012c7-7f58-4b3a-aede-baf0224eb6a2)

But now, there is no link to that notebook:
![Screenshot 2024-12-06 at 10 28 59 AM](https://github.com/user-attachments/assets/ed02dd45-475b-43d3-843c-5eabbf693ff1)

I'm not exactly sure which version of `dms-vep-pipeline-3` this removal occurred. I thought maybe it was a purposeful removal, but I don't see any mention of it in the CHANGELOG, so it might be a bug. Based on my very surface level digging, it appears the notebook is not even being run and put in `/results`. Personally, I found this notebook useful, but if it got removed for some reason I am missing, feel free to close this issue.

**Comment by jbloom** [comment]
It should still be there, I will take a look at what is going on.

**Comment by jbloom** [comment]
I identified the source of this error: right now if `use_precomputed_barcode_counts` is missing from `config.yaml` rather than `false`, they are not built.

So to fix this **without** updating your `dms-vep-pipeline-3` version, simply add `use_precomputed_barcode_counts: false` to your `config.yaml`.

However, I will also fix so that it renders this notebook even if `use_precomputed_barcode_counts` is entirely missing in `config.yaml`.

**Comment by jbloom** [comment]
@bblarsen-sci, thanks for noting this. It is being fixed by #168, which will be in version 3.19 when I finish that.

For now (until I release that version), just add the following to `config.yaml`:
```
use_precomputed_barcode_counts: false
```
That is an optional key, the problem in the prior versions was the notebook wasn't run when that optional key was missing.
