### ISSUE TITLE
Plot same escape metric for replicates that is used for final average plot

### ISSUE THREAD

**Issue by Caleb-Carr** [dms-vep/dms-vep-pipeline-3#46]
I was thinking for consistency and easier viewing, it would be nice to have the individual escape profiles for replicates display the same escape metric by default that is used for the final averaged escape plot. This seems to be in cell 10/11 of `avg_escape.ipynb` where it seems to be hardcoded to display `mean` by default?

**Comment by jbloom** [comment]
Also, use the `functional_effects` filter default for those.

**Comment by jbloom** [comment]
@Caleb-Carr, this is fixed in version 3.3.1. Re-analyze your antibodies with it, and we can discuss. By my eye, it made things look a bit but not always completely better.

Note you will need to add `assays` to `antibody_escape_config.yml` like this: https://github.com/dms-vep/dms-vep-pipeline-3/blob/main/test_example/data/antibody_escape_config.yml#L11-L41
